### ISSUE TITLE
Singular objects are formatted inconsistent with lists of objects in JSON formatting

### ISSUE THREAD

**Issue by markusthoemmes** [kubernetes/klog#256]
/kind bug

**What steps did you take and what happened:**

I setup a `kind` instance with JSON logging for the kubelet on verbosity 10

```yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        v: "10"
        logging-format: "json"
```

Then, I created a pod and grepped the logs for said pod.

A line with multiple pods (using the `"pods"` field) is printed like this

```
{"ts":1628007538403.2212,"caller":"kubelet/kubelet.go:1941","msg":"SyncLoop ADD","v":2,"source":"api","pods":[{"namespace":"default","name":"basic-30fb5d6a-7063-411d-a21e-432ece8bdede"}]}
```

A line with a singular field (using the `"pod"` field) is printed like this

```
{"ts":1628001511209.806,"caller":"config/config.go:383","msg":"Receiving a new pod","v":4,"pod":"default/basic-b7ab1b87-c31d-42f4-94aa-750c5f7f3f5d"}
```

Note the difference: The former prints the objects in a structured way while the latter prints the object in it's `.String()` version. Both are using `klog.ObjectRef` (or `[]klog.ObjectRef` respectively).

**What did you expect to happen:**

I'd expect the format to be consistent, either the `.String()` version or either as a structured object in both situations.

**Anything else you would like to add:**

Filed a PR in K8s to force string formatting: https://github.com/kubernetes/kubernetes/pull/104104.
